language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra
after_failure:
  - "resultsPath=TeamCode/build/outputs/lint-results-debug.xml"
  - "[ -f $resultsPath ] && cat $resultsPath"
notifications:
  slack: meisterdevs:mif0ed8xNKNS9LUoHhV7YEui
