language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-25
    - extra
after_failure:
  - "resultsPath=TeamCode/build/outputs/lint-results-debug.xml"
  - "[ -f $resultsPath ] && cat $resultsPath"
notifications:
  slack: meisterdevs:mif0ed8xNKNS9LUoHhV7YEui
