language: android
android:
  components:
    - tools
    # The BuildTools version used by your project
    - build-tools-25.0.3
    - build-tools-25.0.1
    - platform-tools

    # The SDK version used to compile your project
    - android-25
    - android-19
    - android-21
    - android-22
    - android-23


jdk: oraclejdk8

after_failure:
  - "resultsPath=TeamCode/build/outputs/lint-results-debug.xml"
  - "[ -f $resultsPath ] && cat $resultsPath"
notifications:
  slack: meisterdevs:mif0ed8xNKNS9LUoHhV7YEui
