language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.3

    # The SDK version used to compile your project
    - android-19

after_failure:
  - "resultsPath=TeamCode/build/outputs/lint-results-debug.xml"
  - "[ -f $resultsPath ] && cat $resultsPath"
notifications:
  slack: meisterdevs:mif0ed8xNKNS9LUoHhV7YEui
